import "./globals.css";
import type { Metadata } from "next";
import { Sora } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs'
const sora = Sora({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={sora.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
